default_settings:
  trainer_type: ppo
  hyperparameters:
    batch_size: 1024
    buffer_size: 10240
    beta: 5e-3
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3e-4
    learning_rate_schedule: linear
    num_epoch: 3
  network_settings:
    hidden_units: 128
    num_layers: 2
    normalize: false
    vis_encode_type: simple
    memory:
      memory_size: 128
      sequence_length: 64
  time_horizon: 64
  reward_signals:
    extrinsic:
      strength: 1.0
      gamma: 0.99
behaviors:
  Hummingbird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: false
      vis_encode_type: simple
      memory:
        memory_size: 128
        sequence_length: 64
    time_horizon: 128
    max_steps: 5e6
